USE Tienda
GO

-- 1. CATEGORIAS
CREATE TRIGGER trg_CategoriasModifiedDate
ON CATEGORIAS
AFTER UPDATE
AS
BEGIN
	UPDATE c
	SET ModifiedDate = GETDATE()
	FROM CATEGORIAS c
	INNER JOIN INSERTED i ON i.CategoriaID = c.CategoriaID
END;

-- 2. SUBCATEGORIAS
CREATE TRIGGER trg_SubcategoriasModifiedDate
ON SUBCATEGORIAS
AFTER UPDATE
AS
BEGIN
	UPDATE s
	SET ModifiedDate = GETDATE()
	FROM SUBCATEGORIAS s
	INNER JOIN INSERTED i ON i.SubcategoriaID = s.SubcategoriaID
END;

-- 3. USERS
CREATE TRIGGER trg_UsersModifiedDate
ON USERS
AFTER UPDATE
AS
BEGIN
	UPDATE u
	SET ModifiedDate = GETDATE()
	FROM USERS u
	INNER JOIN INSERTED i ON i.UserID = u.UserID
END;

-- 4. CLIENTES
CREATE TRIGGER trg_ClientesModifiedDate
ON CLIENTES
AFTER UPDATE
AS
BEGIN
	UPDATE c
	SET ModifiedDate = GETDATE()
	FROM CLIENTES c
	INNER JOIN INSERTED i ON i.ClienteID = c.ClienteID
END;

-- 5. TIENDAS
CREATE TRIGGER trg_TiendasModifiedDate
ON TIENDAS
AFTER UPDATE
AS
BEGIN
	UPDATE t
	SET ModifiedDate = GETDATE()
	FROM TIENDAS t
	INNER JOIN INSERTED i ON i.TiendaID = t.TiendaID
END;

-- 6. TARJETAS
CREATE TRIGGER trg_TarjetasModifiedDate
ON TARJETAS
AFTER UPDATE
AS
BEGIN
	UPDATE t
	SET ModifiedDate = GETDATE()
	FROM TARJETAS t
	INNER JOIN INSERTED i ON i.TarjetaID = t.TarjetaID
END;

-- 7. CLIENTE_TARJETA
CREATE TRIGGER trg_ClienteTarjetaModifiedDate
ON CLIENTE_TARJETA
AFTER UPDATE
AS
BEGIN
	UPDATE ct
	SET ModifiedDate = GETDATE()
	FROM CLIENTE_TARJETA ct
	INNER JOIN INSERTED i ON i.ClienteTarjetaID = ct.ClienteTarjetaID
END;

-- 8. DATOS_FACTURA
CREATE TRIGGER trg_DatosFacturaModifiedDate
ON DATOS_FACTURA
AFTER UPDATE
AS
BEGIN
	UPDATE df
	SET ModifiedDate = GETDATE()
	FROM DATOS_FACTURA df
	INNER JOIN INSERTED i ON i.FacturaID = df.FacturaID
END;

-- 9. CLIENTE_FACTURA
CREATE TRIGGER trg_ClienteFacturaModifiedDate
ON CLIENTE_FACTURA
AFTER UPDATE
AS
BEGIN
	UPDATE cf
	SET ModifiedDate = GETDATE()
	FROM CLIENTE_FACTURA cf
	INNER JOIN INSERTED i ON i.ClienteFacturaID = cf.ClienteFacturaID
END;

-- 10. DESCUENTOS
CREATE TRIGGER trg_DescuentosModifiedDate
ON DESCUENTOS
AFTER UPDATE
AS
BEGIN
	UPDATE d
	SET ModifiedDate = GETDATE()
	FROM DESCUENTOS d
	INNER JOIN INSERTED i ON i.DescuentoID = d.DescuentoID
END;

-- 11. INVENTARIO
CREATE TRIGGER trg_InventarioModifiedDate
ON INVENTARIO
AFTER UPDATE
AS
BEGIN
	UPDATE i
	SET ModifiedDate = GETDATE()
	FROM INVENTARIO i
	INNER JOIN INSERTED ins ON ins.ProductoID = i.ProductoID
END;

-- 12. PRODUCTOS
CREATE TRIGGER trg_ProductosModifiedDate
ON PRODUCTOS
AFTER UPDATE
AS
BEGIN
	UPDATE p
	SET ModifiedDate = GETDATE()
	FROM PRODUCTOS p
	INNER JOIN INSERTED i ON i.ItemID = p.ItemID
END;

-- 13. DIRECCIONES
CREATE TRIGGER trg_DireccionesModifiedDate
ON DIRECCIONES
AFTER UPDATE
AS
BEGIN
	UPDATE d
	SET ModifiedDate = GETDATE()
	FROM DIRECCIONES d
	INNER JOIN INSERTED i ON i.DireccionID = d.DireccionID
END;

-- 14. CARRITOS
CREATE TRIGGER trg_CarritosModifiedDate
ON CARRITOS
AFTER UPDATE
AS
BEGIN
	UPDATE c
	SET ModifiedDate = GETDATE()
	FROM CARRITOS c
	INNER JOIN INSERTED i ON i.CarritoID = c.CarritoID
END;

-- 15. ITEMS_CARRITO
CREATE TRIGGER trg_ItemsCarritoModifiedDate
ON ITEMS_CARRITO
AFTER UPDATE
AS
BEGIN
	UPDATE ic
	SET ModifiedDate = GETDATE()
	FROM ITEMS_CARRITO ic
	INNER JOIN INSERTED i ON i.ItemCarritoID = ic.ItemCarritoID
END;

-- 16. PEDIDOS
CREATE TRIGGER trg_PedidosModifiedDate
ON PEDIDOS
AFTER UPDATE
AS
BEGIN
	UPDATE p
	SET ModifiedDate = GETDATE()
	FROM PEDIDOS p
	INNER JOIN INSERTED i ON i.PedidoID = p.PedidoID
END;

-- 17. PAGOS
CREATE TRIGGER trg_PagosModifiedDate
ON PAGOS
AFTER UPDATE
AS
BEGIN
	UPDATE p
	SET ModifiedDate = GETDATE()
	FROM PAGOS p
	INNER JOIN INSERTED i ON i.PagoID = p.PagoID
END;

-- 18. DETALLE_PEDIDO
CREATE TRIGGER trg_DetallePedidoModifiedDate
ON DETALLE_PEDIDO
AFTER UPDATE
AS
BEGIN
	UPDATE dp
	SET ModifiedDate = GETDATE()
	FROM DETALLE_PEDIDO dp
	INNER JOIN INSERTED i ON i.DetallePedidoID = dp.DetallePedidoID
END;