USE Tienda
GO

-- 1. CATEGORIAS
CREATE TRIGGER trg_CategoriasModifiedDate
ON CATEGORIAS
AFTER UPDATE
AS
BEGIN
	UPDATE c
	SET ModifiedDate = GETDATE()
	FROM CATEGORIAS c
	INNER JOIN INSERTED i ON i.CategoriaID = c.CategoriaID
END;

-- 2. SUBCATEGORIAS
CREATE TRIGGER trg_SubcategoriasModifiedDate
ON SUBCATEGORIAS
AFTER UPDATE
AS
BEGIN
	UPDATE s
	SET ModifiedDate = GETDATE()
	FROM SUBCATEGORIAS s
	INNER JOIN INSERTED i ON i.SubcategoriaID = s.SubcategoriaID
END;

-- 3. USERS
CREATE TRIGGER trg_UsersModifiedDate
ON USERS
AFTER UPDATE
AS
BEGIN
	UPDATE u
	SET ModifiedDate = GETDATE()
	FROM USERS u
	INNER JOIN INSERTED i ON i.UserID = u.UserID
END;

-- 4. CLIENTES
CREATE TRIGGER trg_ClientesModifiedDate
ON CLIENTES
AFTER UPDATE
AS
BEGIN
	UPDATE c
	SET ModifiedDate = GETDATE()
	FROM CLIENTES c
	INNER JOIN INSERTED i ON i.ClienteID = c.ClienteID
END;

-- 5. TIENDAS
CREATE TRIGGER trg_TiendasModifiedDate
ON TIENDAS
AFTER UPDATE
AS
BEGIN
	UPDATE t
	SET ModifiedDate = GETDATE()
	FROM TIENDAS t
	INNER JOIN INSERTED i ON i.TiendaID = t.TiendaID
END;

-- 6. DESCUENTOS
CREATE TRIGGER trg_DescuentosModifiedDate
ON DESCUENTOS
AFTER UPDATE
AS
BEGIN
	UPDATE d
	SET ModifiedDate = GETDATE()
	FROM DESCUENTOS d
	INNER JOIN INSERTED i ON i.DescuentoID = d.DescuentoID
END;

-- 7. INVENTARIO
CREATE TRIGGER trg_InventarioModifiedDate
ON INVENTARIO
AFTER UPDATE
AS
BEGIN
	UPDATE i
	SET ModifiedDate = GETDATE()
	FROM INVENTARIO i
	INNER JOIN INSERTED ins ON ins.ProductoID = i.ProductoID
END;

-- 8. PRODUCTOS
CREATE TRIGGER trg_ProductosModifiedDate
ON PRODUCTOS
AFTER UPDATE
AS
BEGIN
	UPDATE p
	SET ModifiedDate = GETDATE()
	FROM PRODUCTOS p
	INNER JOIN INSERTED i ON i.ItemID = p.ItemID
END;

-- 9. DIRECCIONES
CREATE TRIGGER trg_DireccionesModifiedDate
ON DIRECCIONES
AFTER UPDATE
AS
BEGIN
	UPDATE d
	SET ModifiedDate = GETDATE()
	FROM DIRECCIONES d
	INNER JOIN INSERTED i ON i.DireccionID = d.DireccionID
END;

-- 10. COMPRAS
CREATE TRIGGER trg_ComprasModifiedDate
ON COMPRAS
AFTER UPDATE
AS
BEGIN
	UPDATE c
	SET ModifiedDate = GETDATE()
	FROM COMPRAS c
	INNER JOIN INSERTED i ON i.CompraID = c.CompraID
END;

-- 11. VENTAS
CREATE TRIGGER trg_VentasModifiedDate
ON VENTAS
AFTER UPDATE
AS
BEGIN
	UPDATE v
	SET ModifiedDate = GETDATE()
	FROM VENTAS v
	INNER JOIN INSERTED i ON i.VentaID = v.VentaID
END;

-- 12. DETALLE_VENTA
CREATE TRIGGER trg_DetalleVentaModifiedDate
ON DETALLE_VENTA
AFTER UPDATE
AS
BEGIN
	UPDATE dv
	SET ModifiedDate = GETDATE()
	FROM DETALLE_VENTA dv
	INNER JOIN INSERTED i ON i.DetalleVentaID = dv.DetalleVentaID
END;

-- 13. TARJETAS
CREATE TRIGGER trg_TarjetasModifiedDate
ON TARJETAS
AFTER UPDATE
AS
BEGIN
	UPDATE t
	SET ModifiedDate = GETDATE()
	FROM TARJETAS t
	INNER JOIN INSERTED i ON i.TarjetaID = t.TarjetaID
END;

-- 14. DATOS_FACTURA
CREATE TRIGGER trg_DatosFacturaModifiedDate
ON DATOS_FACTURA
AFTER UPDATE
AS
BEGIN
	UPDATE df
	SET ModifiedDate = GETDATE()
	FROM DATOS_FACTURA df
	INNER JOIN INSERTED i ON i.FacturaID = df.FacturaID
END;

-- 15. PAGOS
CREATE TRIGGER trg_PagosModifiedDate
ON PAGOS
AFTER UPDATE
AS
BEGIN
	UPDATE p
	SET ModifiedDate = GETDATE()
	FROM PAGOS p
	INNER JOIN INSERTED i ON i.PagoID = p.PagoID
END;